Repository swoldbye/Nordstjernen, pull requests merged in 2020-01, with the labels that each got.

#96 Opdateret Togtobserver
  app/src/androidTest/java/com/example/skibslogapp/SQLTest.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/EtapeDAO.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/LogpunktDAO.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/TogtDAO.java
  app/src/main/java/com/example/skibslogapp/model/Togt.java
Labels: need to have, optimering

#113 Opret Første Etape
  app/src/main/java/com/example/skibslogapp/etapeoversigt/EtapeOversigt_frag.java
  app/src/main/java/com/example/skibslogapp/model/Etape.java
  app/src/main/java/com/example/skibslogapp/view/opretEtape/OpretEtapeDialog.java
  app/src/main/res/layout/fragment_etape_oversigt.xml
Labels: need to have

#115 Fixet Database Connector leaks
  app/src/main/java/com/example/skibslogapp/datalayer/global/DbEtapeStringify.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/EtapeDAO.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/LogpunktDAO.java
  app/src/main/java/com/example/skibslogapp/datalayer/local/TogtDAO.java
Labels: need to have, optimering

#170 Add: Skipper to besætning
  app/src/main/java/com/example/skibslogapp/view/oprettogt/OpretTogt_frag.java
Labels: bug, need to have
